### ISSUE TITLE
希望对 npm 命令路径的处理更智能些

### ISSUE THREAD

**Issue by zaaack** [qiu8310/smart-npm#51]
```sh
z at ZsMBP in ~ 
$ yarn global bin
/usr/local/bin

z at ZsMBP in ~ 
$ snpm
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/z/.config/yarn/global/node_modules/.bin/npm ENOENT
    at exports._errnoException (util.js:1012:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

**Comment by qiu8310** [comment]
谢谢反馈，我处理下！

**Comment by qiu8310** [comment]
发了一个 3.0.1 版本，应该解决了这问题

猜测应该是 yarn 安装的时候没有重复安装 npm，导致 snpm 找不到它目录下的 npm。现在做了兼容，如果找不到 npm 的话就直接用系统的 npm 了

**Comment by zaaack** [comment]
感谢你的修复，不过我最终选择这样做了:

```sh
alias onpm=npm --registry=https://registry.npmjs.org/
```
